### ISSUE TITLE
FAQ section on www.orchid.com

### ISSUE THREAD

**Issue by Salvatore-Official** [OrchidProtocol/www.orchid.com#147]
Dear sirs, madams,

I trust you are well.

I have several suggestions for the Orchid site and I'm going to raise requests in here in order to keep track of them.

I'm active in the Official Community Group on Telegram but I think GitHub is a better place for suggestions - this way, we can make improvements faster.

I navigate through the hops of Orchid from my Android device using Google Chrome and I often see minor "bugs" in the website interface.

Some of them have already been fixed by notifying Derek Silva, who probably passed my feedback onto you guys. So, cheers for that.

However, the FAQ section needs a nice revamp, in my opinion. I had suggested to make it similar to what Microsoft has at the moment on their site.

For now, please be aware of the following issue and suggestion:

Issue.

When I tap on an FAQ, it scrolls all the way down to the answer - however, the banner on top covers the first few lines of the answer. See screenshots below.

![Screenshot_20210118-093244_Chrome.jpg](https://user-images.githubusercontent.com/75791773/104891601-74c24f80-5971-11eb-861f-489399198f8b.jpg)

![Screenshot_20210118-093337_Chrome.jpg](https://user-images.githubusercontent.com/75791773/104891648-8572c580-5971-11eb-88e2-72cc89aeb4cf.jpg)

As you can see, "What is Orchid?" doesn't show clearly and I need to scroll up a bit for me to read the full answer. This is happening with all the FAQs. 

Suggestion.

Can the FAQ section be added to the menu panel on the right as well? At the moment, users have to scroll all the way down in order to find it. See screenshot below.

![Screenshot_20210118-093420_Chrome.jpg](https://user-images.githubusercontent.com/75791773/104891914-d1256f00-5971-11eb-8792-4e45c637c68b.jpg)

This is my first time I'm raising an issue on GitHub and I'm using the app as well. Apologies if I made a mistake or if this is not the right place for my message.

Keep up the great work, guys! 

Thanks and Regards,
Salvatore

**Comment by diabeticpilot** [comment]
Thanks for the notes - we can add the FAQ to the main nav. The other issues are fixed.
