### ISSUE TITLE
Orchid’s “Follow the White Rabbit” Podcast is Hopping Onto Audius - is it though?! 🤔 

### ISSUE THREAD

**Issue by Salvatore-Official** [OrchidProtocol/www.orchid.com#166]
Hello Orchid officials, 

I hope you are well.

Last November, Orchid published an article in the blog announcing that Audius, the "Decentralized Spotify", was going to host the FTWR podcast.

If I'm correct, this is the official page on Audius:

https://audius.co/ftwr_podcast

I'm opening this issue now because there is no Audius platform link on the Orchid site (https://www.orchid.com/podcast#subscribe) ...and I can't see any playlists published on Audius, either... 

The Google Podcasts link is also missing (https://podcasts.google.com/feed/aHR0cHM6Ly9mb2xsb3d0aGV3aGl0ZXJhYmJpdC5saWJzeW4uY29tL3Jzcw?ep=14) - I have copied the link from the podcast page directly and there seems to be an error in the Url. The link from the Google Podcast Publisher Tool generated using <https://followthewhiterabbit.libsyn.com/rss> gives the following Feed ID: **aHR0cHM6Ly9mb2xsb3d0aGV3aGl0ZXJhYmJpdC5saWJzeW4uY29tL3Jzcw**

The "_?ep=14_" bit should be removed from the Url, in my opinion. 

Thanks and Regards,
_Salvatore_

**Comment by diabeticpilot** [comment]
Closing this issue as we have since decided to stop publishing on Audius. The Google podcast links are linked for each episode.
